/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

var utils = require('ffwd-utils/server');

module.exports = function(config) {
  console.info('config', config);
  return {};
};