/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

module.exports = function(grunt) {
  grunt.registerTask('scripts', function(target) {
    target = target || 'prod';
    var tasks = [];
    var pkg = grunt.config().pkg;
    var name = pkg.ffwd.scriptsCompiler;

    if (name && name !== 'none') {
      tasks.push(name +':'+ target);

      if (name === 'requirejs') {
        // should do some magick for requirejs...
      }
      else {
        // do some magick for browserify...
        tasks.push('uglify');
      }
    }

    grunt.task.run(tasks);
  });
};