/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

module.exports = function(grunt) {
  grunt.registerTask('scripts', function(target) {
    target = target || 'prod';
    var tasks = [];
    var pkg = grunt.config().pkg;
    var scriptsCompiler = pkg.ffwd.scriptsCompiler;
    var stylesCompiler = pkg.ffwd.stylesCompiler;

    if (scriptsCompiler && scriptsCompiler != 'none') {
      tasks.push(scriptsCompiler +':'+ target);
      
      if (scriptsCompiler === 'requirejs' && stylesCompiler && stylesCompiler != 'none') {
        tasks.push(stylesCompiler +':'+ target);
      }
    }

    grunt.task.run(tasks);
  });
};