/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

module.exports = function(grunt) {
  grunt.registerTask('styles', function(target) {
    target = target || 'prod';
    var tasks = [];
    var pkg = grunt.config().pkg;

    if (pkg.ffwd.stylesCompiler && pkg.ffwd.stylesCompiler != 'none') {
      tasks.push(pkg.ffwd.stylesCompiler +':'+ target);
    }

    grunt.task.run(tasks);
  });
};