/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

module.exports = {
  options: {
    bundleOptions: {
      standalone: '<%= _.camelize(pkg.name) %>'
    }
  },

  prod: {
    files: {
      '<%= pkg.ffwd.dist %>/scripts/<%= pkg.name %>.js': ['./client/scripts/index.js']
    }
  },

  dev: {
    files: {
      '<%= pkg.ffwd.dist %>/scripts/<%= pkg.name %>.js': ['./client/scripts/index.js']
    }
  }
};