/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

module.exports = [
  '<%= pkg.ffwd.dist %>',
  '.tmp',
  'doc/server',
  'doc/client'
];