/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

module.exports = function(config) {
  return {
    options: {
      importPath: [
        'client/bower_components/foundation/scss'
      ],
      relativeAssets: true,
      outputStyle: 'nested',
      fontsDir: 'client/fonts',
      sassDir: 'client/sass',
      cssDir: '<%= pkg.ffwd.dist %>/styles'
    },
    dev: {},
    prod: {
      options: {
        outputStyle: 'compressed',
        environment: 'production'
      }
    }
  };
}