/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

module.exports = function(config) {
  config.livereloadPort = config.livereloadPort || (1 + config.port)

  return {
    options: {
      livereload: false,
      hostname: '*'
    },
    
    prod: {
      options: {
        server: 'app.js'
      }
    },

    dev: {
      options: {
        server: 'demo.js',
        livereload: config.livereloadPort,
        // conflicts with "watch" task...
        // serverreload: true,
        showStack: true
      }
    }
  };
};