/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

module.exports = {
  options: {
    plugins: [
      'plugins/markdown'
    ],
    markdown: {
      parser: 'gfm'
    },
    explain: true
  },
  client: {
    options: {
      destination: 'doc/client',
      explain: true
    },
    src: [
      'client/README.md',
      'client/scripts/**/*.js',
      'test/client/**/*.js'
    ]
  },
  server: {
    options: {
      destination: 'doc/server',
      explain: true
    },
    src: [
      'client/README.md',
      'server/**/*.js',
      'test/server/**/*.js'
    ]
  }
};