/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

module.exports = {
  options: {
    jshintrc: true
  },
  client: {
    files: {
      src: [
        'client/scripts/**/*.js'
      ]
    }
  },
  server: {
    files: {
      src: [
        'server/**/*.js'
      ]
    }
  },
  test: {
    files: {
      src: [
        'test/**/*.js'
      ]
    }
  }
};