/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

var config = {
  options: {
    configFile: 'test/client.conf.js'
  },
  // unit: {},
  chrome: {
    browsers: ['Chrome']
  },
  phantomjs: {
    browsers: ['PhantomJS']
  },
  continuous: {
    singleRun: true,
    browsers: ['PhantomJS']
  }
};

module.exports = config;
