/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

var utils = require('ffwd-utils/server');


function featuresFiles(wanted) {
  wanted = wanted || '**/*.js';
  var files = [];

  utils._.each(utils.features(), function(fPath, fName) {
    files.push(fPath +'/client/scripts/'+ wanted);
    files.push(fPath +'/server/'+ wanted);
  });

  return files;
}

module.exports = function(config) {
  var jsFiles = [
        'grunt/**/*.js',
        'server/**/*.js',
        'client/scripts/**/*.js'
      ].concat(featuresFiles());

  return {
    options: {
      livereload: false
    },
    
    scripts: {
      files: [
        'client/scripts/**/*.js'
      ],
      tasks: [
        'newer:jshint:client',
        'scripts:dev'
      ]
    },

    styles: {
      files: [
        'client/{styles,less}/**/*.{less,css}',
        'client/{style,sass,scss}/**/*.{scss,sass,css}'
      ],
      tasks: [
        'styles:dev'
      ]
    },

    doc: {
      files: jsFiles,
      tasks: [
        'ffwd-doc'
      ]
    }
  };
}